version: "2"
services:
  mongo_catalog:
    image: mongo:3.4.2
    container_name: mongo_linx
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=suasenha
    ports:
      - "27017:27017"
    command: mongod
  redis_catalog:
    image: "redis:alpine"
    container_name: redis_catalog
    command: redis-server --requirepass suasenha
    ports:
      - "6379:6379"
  redis_recommendation:
    image: "redis:alpine"
    container_name: redis_rec
    command: redis-server --requirepass suasenha --port 6380
    ports:
      - "6380:6380"